package org.isatools.isatab.submit.sra;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.RequestLine;
import org.apache.http.StatusLine;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.mime.HttpMultipartMode;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.entity.mime.content.FileBody;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

import java.io.File;


/**
 * Created by the ISATeam.
 * User: agbeltran
 * Date: 25/09/2013
 * Time: 11:41
 *
 *
 * Programmatic submission to ENA.
 *
 * See documentation at http://www.ebi.ac.uk/ena/about/training/sra_rest_tutorial
 *
 * @author <a href="mailto:alejandra.gonzalez.beltran@gmail.com">Alejandra Gonzalez-Beltran</a>
 *
 */
public class SRASubmission {

    String ENA_REST_DEVURL="https://wwwdev.ebi.ac.uk";
    String ENA_REST_TESTURL="https://www-test.ebi.ac.uk";
    String ENA_REST_PRODURL="https://www.ebi.ac.uk";

    private static String SUBMISSION = "SUBMISSION"; //mandatory
    private static String SAMPLE = "SAMPLE";
    private static String STUDY = "STUDY";
    private static String EXPERIMENT = "EXPERIMENT";
    private static String RUN = "RUN";
    private static String ANALYSIS = "ANALYSIS";
    private static String DAC = "DAC"; //for EGA submissions only
    private static String POLICY = "POLICY"; // for EGA submissions only
    private static String DATASET = "DATASET"; //for EGA submissions only
    private static String PROJECT = "PROJECT";

    private static String SUBMISSION_FILE = "submission.xml"; //mandatory
    private static String SAMPLE_FILE = "sample_set.xml";
    private static String STUDY_FILE = "study.xml";
    private static String EXPERIMENT_FILE = "experiment_set.xml";
    private static String RUN_FILE = "run_set.xml";
    private static String ANALYSIS_FILE = "analysis.xml";
    private static String DAC_FILE = "dac.xml"; //for EGA submissions only
    private static String POLICY_FILE = "policy.xml"; // for EGA submissions only
    private static String DATASET_FILE = "dataset.xml"; //for EGA submissions only
    private static String PROJECT_FILE = "project.xml";

    //this is the URL generated by the SRAURLGenerator - putting a dummy one to push to github
    String URL = "https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/?auth=ERA%20era-drop...";

    public void postFile(String dirName) throws Exception{

        HttpClient client = HttpClientBuilder.create().build();
        HttpPost post = new HttpPost(URL);

        MultipartEntityBuilder multipartEntity = MultipartEntityBuilder.create();
        multipartEntity.setMode(HttpMultipartMode.BROWSER_COMPATIBLE);


        File directory = new File(dirName);
        File[] files = directory.listFiles();

        for(File file : files){

            String fileName = file.getName();

            if (fileName.equals(SUBMISSION_FILE)){

                multipartEntity.addPart(SUBMISSION, new FileBody(file));

            } else if (fileName.equals(SAMPLE_FILE)){

                multipartEntity.addPart(SAMPLE, new FileBody(file));

            } else if (fileName.equals(STUDY_FILE)) {

                multipartEntity.addPart(STUDY, new FileBody(file));

            }  else if (fileName.equals(EXPERIMENT_FILE)) {

                multipartEntity.addPart(EXPERIMENT, new FileBody(file));

            } else if (fileName.equals(RUN_FILE)) {

                multipartEntity.addPart(RUN, new FileBody(file));

            }  else if (fileName.equals(ANALYSIS_FILE)) {

                multipartEntity.addPart(ANALYSIS, new FileBody(file));

            }

        }
        post.setEntity(multipartEntity.build());

        RequestLine requestLine = post.getRequestLine();
        System.out.println("requestLine="+requestLine);

        HttpResponse response = client.execute(post);
        HttpEntity entity = response.getEntity();

        String responseString = EntityUtils.toString( entity, "UTF-8" );
        System.out.println("responseString="+responseString);

        StatusLine statusLine = response.getStatusLine();  // CONSIDER  Detect server complaints
        System.out.println(statusLine);

        EntityUtils.consume(entity);

    }

    public static void main(String[] args) throws Exception {

        SRASubmission submission = new SRASubmission();
        submission.postFile("/Users/agbeltran/Documents/sra/BII-S-7");

    }

}
