package org.isatools.isatab.submit.sra;

import org.apache.http.HttpEntity;
import org.apache.http.HttpResponse;
import org.apache.http.RequestLine;
import org.apache.http.StatusLine;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.mime.HttpMultipartMode;
import org.apache.http.entity.mime.MultipartEntityBuilder;
import org.apache.http.entity.mime.content.FileBody;
import org.apache.http.impl.client.HttpClientBuilder;
import org.apache.http.util.EntityUtils;

import java.io.File;


/**
 * Created by the ISATeam.
 * User: agbeltran
 * Date: 25/09/2013
 * Time: 11:41
 *
 * http://www.ebi.ac.uk/ena/about/training/sra_rest_tutorial#part4
 *
 * @author <a href="mailto:alejandra.gonzalez.beltran@gmail.com">Alejandra Gonzalez-Beltran</a>
 *
 *
 * //SUBMISSION (mandatory), SAMPLE, STUDY, EXPERIMENT, RUN, ANALYSIS, DAC (for EGA submissions only), POLICY (for EGA submissions only), DATASET (foe EGA submissions only) and PROJECT.
 *
 */
public class SRASubmission {

    String ENA_REST_DEVURL="https://wwwdev.ebi.ac.uk";
    String ENA_REST_TESTURL="https://www-test.ebi.ac.uk";
    String ENA_REST_PRODURL="https://www.ebi.ac.uk";


    //this is the URL generated by the SRAURLGenerator - putting a dummy one to push to github
    String URL = "https://wwwdev.ebi.ac.uk/ena/submit/drop-box/submit/?auth=ERA%20era-drop...";

    public void postFile(String fileName) throws Exception{

        HttpClient client = HttpClientBuilder.create().build();
        HttpPost post = new HttpPost(URL);

        MultipartEntityBuilder multipartEntity = MultipartEntityBuilder.create();
        multipartEntity.setMode(HttpMultipartMode.BROWSER_COMPATIBLE);

        File file = new File(fileName);

        multipartEntity.addPart("SUBMISSION", new FileBody(file));

        post.setEntity(multipartEntity.build());

        RequestLine requestLine = post.getRequestLine();
        System.out.println("requestLine="+requestLine);

        HttpResponse response = client.execute(post);
        HttpEntity entity = response.getEntity();

        String responseString = EntityUtils.toString( entity, "UTF-8" );
        System.out.println("responseString="+responseString);

        StatusLine statusLine = response.getStatusLine();  // CONSIDER  Detect server complaints
        System.out.println(statusLine);

        EntityUtils.consume(entity);

    }

    public static void main(String[] args) throws Exception {

        SRASubmission submission = new SRASubmission();
        submission.postFile("/Users/agbeltran/Desktop/sra/BII-S-7/submission.xml");

    }

}
